### PR TITLE
Create mint_nft offchain script

### PR DESCRIPTION
**Pull request by juliusfrost**
For some reason when I try to mint the wrong amount (>1) it still mints. I then tried adding `assert False` in `nft.py` but it still validates. @nielstron

### CODE REVIEW

**Comment by nielstron** [comment]
You need to make sure to bind all parameters of the script. If not all parameters are bound, the script is not executed and _passes_.

Not that minting scripts only take two parameters unless "--force-three-params" is set at compile time.

**Comment by nielstron** [comment]
You need to make sure to bind all parameters of the script. If not all parameters are bound, the script is not executed and _passes_. (the function returns a non-executed, partially bound functions)

Not that minting scripts only take two parameters unless "--force-three-params" is set at compile time.

**Comment by nielstron** [comment]
In this particular case you can either remove the datum parameter or set --force-three-params

**Comment by juliusfrost** [comment]
I got rid of the datum but I get error from the node:

```
An error has occurred:  User error:
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.
Caused by: [
  (builtin unBData)
  (con
    data
    #d8799fd8799f58201cf5717d6564e05794ee7d0ae265260f75bb87f6db0cabae931309a14a420427ff01ff
  )
]
```

**Comment by nielstron** [comment]
The parameters are passed into the contract in the wrong order :)

**Comment by nielstron** [comment]
I hope that hard to debug errors like this will be clarified by  https://github.com/OpShin/opshin/pull/112

**Comment by nielstron** [comment]
That said, thank you for raising the issue and I hope this will save future developers some time.

Feel free to let me know if you think the changes will help and if you could think of other features that would help at developing!

**Comment by juliusfrost** [comment]
> That said, thank you for raising the issue and I hope this will save future developers some time.
> 
> Feel free to let me know if you think the changes will help and if you could think of other features that would help at developing!

For me I think adding more python functions in opshin would make the experience nicer with syntactic sugars. I would implement the functions myself but I'm not sure how to start understanding pluthon and uplc.

**Comment by nielstron** [comment]
Hm a lot of these functions can be implemented in plain python too? Feel free to open an enhancement issue at `opshin` for your wishlist of sugar functions! Don't worry about the issue format, you can just put a list + description of what it does and I'll have a look

**Comment by juliusfrost** [comment]
> Hm a lot of these functions can be implemented in plain python too? Feel free to open an enhancement issue at `opshin` for your wishlist of sugar functions! Don't worry about the issue format, you can just put a list + description of what it does and I'll have a look

I do mean plain python. That is just implementing more of the python language support in opshin. Sometime I have to hack a workaround for a function in python that's not yet implemented in opshin (for example dict items).

**Pull request merged**
