### PR TITLE
Update dependencies (opshin 0.14.1 and pycardano 0.9.0)

### PR DESCRIPTION
**Pull request by juliusfrost**

### CODE REVIEW

**Comment by juliusfrost** [comment]
@nielstron Not sure what happened with pycardano 0.9.0 but it broke PlutusData conversion of primitives with pyaiken
https://github.com/OpShin/opshin-pioneer-program/actions/runs/5063242021/jobs/9089632567?pr=68#step:10:119

**Comment by nielstron** [comment]
The issue is not from PyCardano but from constant folding. It produces this constant, which causes a hickup in pyaiken/uplc: `                                                 (con
                                                                                  list
                                                                                  <pair<data, data>>
                                                                                  [(#40, #00)]
                                                                                )`

**Comment by nielstron** [comment]
Appearently the uplc package is broken, as pairs are written using `[` / `]` in the lastest aiken version: https://aiken-lang.org/uplc/syntax

**Comment by nielstron** [comment]
The issue appears to come from pyaiken.uplc.unflat hinting at a bug in aiken. It can be fixed by using the unflatter in the uplc package instead :) Tagging @rvcas (will open an issue there later)

**Comment by nielstron** [comment]
Side note: build artifacts should best be gitignored :)

**Comment by juliusfrost** [comment]
This looks great! Thanks @nielstron !

**Pull request merged**
