### PR TITLE
Attempt Lucid offchain code with local node

### PR DESCRIPTION
**Pull request by juliusfrost**
I attempt to use Kupo and Ogmios to connect to lucid to the local cardano node. This is so we don't have to use the blockfrost API

Update: currently waiting on https://github.com/CardanoSolutions/kupo/issues/111

### CODE REVIEW

**Comment by nielstron** [comment]
Hm you should not need to use lucid to connect to ogmios/kupo

**Comment by nielstron** [comment]
There is an ogmios backend for PyCardano as well :)

**Comment by nielstron** [comment]
Just saw that you use that in #13

**Comment by juliusfrost** [comment]
> Hm you should not need to use lucid to connect to ogmios/kupo

Lucid need a [provider](https://deno.land/x/lucid@0.9.4/mod.ts?s=Provider) to query and submit transactions to the blockchain. There's two providers available: [Blockfrost](https://deno.land/x/lucid@0.9.4/mod.ts?s=Blockfrost) and [Kupmios](https://deno.land/x/lucid@0.9.4/mod.ts?s=Kupmios) (Kupo + Ogmios )

**Pull request closed without merging**
